### ISSUE TITLE
HTML Issues

### ISSUE THREAD

**Issue by sectroyer** [hvqzao/report-ng#5]
When I use:
`Description: '<html><b>test</b></html>'`
generated document doesn't open in Word. No such issue with:
`Recommendation: '<html><b>test</b></html>'`
for example.

Also <img> tag wasn't working and I wasn't getting any error (report was generated without the picture). After manually modifying the source code I finally got relevant info:
```
ERROR: No module named PIL
Report saved.

```

**Comment by hvqzao** [comment]
It is likely that template you are using has different types of placeholders for Description and Recommendation.

Generally report-ng handles two types of them - Inline (`<ihtml>`) and Regular (`<html>`), each handling different types of tags.
For more details please refer to README at https://github.com/hvqzao/report-ng (Inline pseudo-html allowed tags and Regular ones for more details).
