### ISSUE TITLE
Multiple Request/Response support

### ISSUE THREAD

**Issue by sectroyer** [hvqzao/report-ng#6]
It would be nice to have multiple request/response support. If template already declares them it would be nice to define Example2,Example3,etc. sections or something like this.

**Comment by hvqzao** [comment]
You can create your template and put multiple request response blocks and wrap them in conditional tags. This way if these blocks will not be set, they will not be shown in generated document. Please refer to project README.md which describes conditional. You should probably find some samples in examples directory.
